export const Action_Types = {
    SET_PRODUCS : "SET_PRODUCS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART : "ADD_TO_CART",
    CLEAR_CART : "CLEAR_CART"
}